-- Preserve the four synthetic rows and their original integer IDs.
begin;
alter table public.defense_notes add column if not exists note_id uuid not null default gen_random_uuid();
create unique index if not exists defense_notes_note_id_key on public.defense_notes(note_id);
do $$ begin
  if not exists (select 1 from information_schema.columns
    where table_schema='public' and table_name='defense_notes' and column_name='id' and is_identity='YES') then
    alter table public.defense_notes alter column id add generated by default as identity;
  end if;
end $$;
select setval(pg_get_serial_sequence('public.defense_notes','id'),
  greatest(coalesce((select max(id) from public.defense_notes),0)+1,1), false);
alter table public.defense_notes enable row level security;
revoke all on public.defense_notes from public, anon, authenticated;
grant select, insert, update, delete on public.defense_notes to service_role;
grant usage, select on sequence public.defense_notes_id_seq to service_role;
-- No auth.users foreign key: the official judge uses separately verified synthetic identities.
commit;
